import hashlib
import json
from pathlib import Path

from patientcapital.api.app import app

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SNAPSHOT = Path(__file__).with_name("openapi-v1.sha256")
TYPESCRIPT_CONTRACT = PROJECT_ROOT / "web/app/api-types.ts"

PUBLIC_PATHS = {
    "/health/live",
    "/health/ready",
    "/v1/profile",
    "/v1/assets",
    "/v1/assets/{asset_id}",
    "/v1/assets/{asset_id}/prices",
    "/v1/transactions",
    "/v1/transaction-drafts/text",
    "/v1/transaction-drafts/manual",
    "/v1/transaction-drafts/image",
    "/v1/transaction-drafts/{draft_id}",
    "/v1/transaction-drafts/{draft_id}/decisions",
    "/v1/portfolio",
    "/v1/analytics/overview",
    "/v1/alerts",
    "/v1/alerts/{alert_id}/acknowledgements",
    "/v1/monitor-runs",
    "/v1/recommendations",
    "/v1/recommendations/{run_id}",
    "/v1/discovery/recommendations",
    "/v1/proposal-sets",
    "/v1/proposal-sets/{proposal_set_id}",
    "/v1/market-research/latest",
}

PUBLIC_SCHEMAS = {
    "AssetResponse",
    "AnalyticsMoneyMetricResponse",
    "AnalyticsOverviewResponse",
    "AlertAcknowledgementResponse",
    "DiscoveryCandidateResponse",
    "DividendResearchResponse",
    "MonitorAlertResponse",
    "MonitorRunResponse",
    "MarketResearchStatusResponse",
    "MarketSearchResponse",
    "PortfolioResponse",
    "PriceResponse",
    "PriceFreshnessAssetResponse",
    "PriceFreshnessResponse",
    "ProfileResponse",
    "RecommendationResponse",
    "RejectedDiscoveryCandidateResponse",
    "ResearchCitationResponse",
    "TransactionResponse",
    "TransactionDraftFields",
    "TransactionDraftManualCreate",
    "TransactionDraftDecisionCreate",
    "TransactionDraftDecisionResponse",
    "TransactionDraftResponse",
    "TransactionDraftTextCreate",
    "ProposalSetResponse",
}


def test_openapi_v1_matches_snapshot_and_generated_typescript_surface() -> None:
    schema = app.openapi()
    canonical = json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()

    assert hashlib.sha256(canonical).hexdigest() == SNAPSHOT.read_text().strip()
    assert set(schema["paths"]) == PUBLIC_PATHS

    typescript = TYPESCRIPT_CONTRACT.read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript" in typescript
    for path in PUBLIC_PATHS:
        assert f'"{path}"' in typescript
    for schema_name in PUBLIC_SCHEMAS:
        assert f"{schema_name}: {{" in typescript
