/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Get */
        get: operations["profile_get_v1_profile_get"];
        /** Profile Put */
        put: operations["profile_put_v1_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assets Get */
        get: operations["assets_get_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Asset Put */
        put: operations["asset_put_v1_assets__asset_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{asset_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price Post */
        post: operations["price_post_v1_assets__asset_id__prices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Post */
        post: operations["transaction_post_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction-drafts/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Draft Text Post */
        post: operations["transaction_draft_text_post_v1_transaction_drafts_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction-drafts/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Draft Manual Post */
        post: operations["transaction_draft_manual_post_v1_transaction_drafts_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction-drafts/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Draft Image Post */
        post: operations["transaction_draft_image_post_v1_transaction_drafts_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transaction Draft Get */
        get: operations["transaction_draft_get_v1_transaction_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction-drafts/{draft_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Draft Decision Post */
        post: operations["transaction_draft_decision_post_v1_transaction_drafts__draft_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Get */
        get: operations["portfolio_get_v1_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommendation Post */
        post: operations["recommendation_post_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discovery Recommendation Post */
        post: operations["discovery_recommendation_post_v1_discovery_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposal-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Proposal Set Post */
        post: operations["proposal_set_post_v1_proposal_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposal-sets/{proposal_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposal Set Get */
        get: operations["proposal_set_get_v1_proposal_sets__proposal_set_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendation Get */
        get: operations["recommendation_get_v1_recommendations__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetListResponse */
        AssetListResponse: {
            /** Assets */
            assets: components["schemas"]["AssetResponse"][];
        };
        /** AssetPut */
        AssetPut: {
            /** Expected Version */
            expected_version?: number | null;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Lot Size */
            lot_size: number;
            /** Target Weight */
            target_weight: number | string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** AssetResponse */
        AssetResponse: {
            /** Asset Id */
            asset_id: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Lot Size */
            lot_size: number;
            /** Target Weight */
            target_weight: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_transaction_draft_image_post_v1_transaction_drafts_image_post */
        Body_transaction_draft_image_post_v1_transaction_drafts_image_post: {
            /** File */
            file: string;
        };
        /** DiscoveryCandidateResponse */
        DiscoveryCandidateResponse: {
            /** Asset Id */
            asset_id: string;
            /** Name */
            name: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "ofz" | "equity_index_fund";
            /** Target Weight */
            target_weight: string;
            /** Rationale */
            rationale: string;
            /** Unit Price */
            unit_price: string;
            /** Lot Size */
            lot_size: number;
            /** Lot Cost */
            lot_cost: string;
            /**
             * Price As Of
             * Format: date-time
             */
            price_as_of: string;
            /** Quote Kind */
            quote_kind: string;
            /** Turnover */
            turnover: string;
            /** Maturity Date */
            maturity_date?: string | null;
            /** Yield Percent */
            yield_percent?: string | null;
            /** Source Url */
            source_url: string;
            /** Classification Url */
            classification_url: string;
        };
        /** DiscoveryRecommendationCreate */
        DiscoveryRecommendationCreate: {
            /** Contribution */
            contribution: number | string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** PortfolioAssetResponse */
        PortfolioAssetResponse: {
            /** Asset Id */
            asset_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Currency */
            currency: string;
            /** Latest Price */
            latest_price: string;
            /**
             * Price As Of
             * Format: date-time
             */
            price_as_of: string;
            /** Market Value */
            market_value: string;
            /** Cost Basis */
            cost_basis: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
            /** Target Weight */
            target_weight: string;
            /** Actual Weight */
            actual_weight: string;
            /** Drift */
            drift: string;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Currency */
            currency: string;
            /** Total Market Value */
            total_market_value: string;
            /** Total Cost Basis */
            total_cost_basis: string;
            /** Total Unrealized Pnl */
            total_unrealized_pnl: string;
            /** Assets */
            assets: components["schemas"]["PortfolioAssetResponse"][];
        };
        /** PriceCreate */
        PriceCreate: {
            /** Price */
            price: number | string;
            /** Currency */
            currency: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Max Age Seconds */
            max_age_seconds: number;
            /** Source */
            source: string;
        };
        /** PriceResponse */
        PriceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Asset Id */
            asset_id: string;
            /** Price */
            price: string;
            /** Currency */
            currency: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Max Age Seconds */
            max_age_seconds: number;
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfilePut */
        ProfilePut: {
            /** Expected Version */
            expected_version?: number | null;
            /** Base Currency */
            base_currency: string;
            /** Investment Horizon Years */
            investment_horizon_years: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "conservative" | "balanced" | "growth";
            /** Cash Buffer */
            cash_buffer: number | string;
            /** Broker Name */
            broker_name: string;
            /** Fee Rate */
            fee_rate: number | string;
            /** Minimum Fee */
            minimum_fee: number | string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Version */
            version: number;
            /** Base Currency */
            base_currency: string;
            /** Investment Horizon Years */
            investment_horizon_years: number;
            /** Risk Level */
            risk_level: string;
            /** Cash Buffer */
            cash_buffer: string;
            /** Broker Name */
            broker_name: string;
            /** Fee Rate */
            fee_rate: string;
            /** Minimum Fee */
            minimum_fee: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProposalSetCreate */
        ProposalSetCreate: {
            /** Contribution */
            contribution: number | string;
        };
        /** ProposalSetResponse */
        ProposalSetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Contribution */
            contribution: string;
            /** Currency */
            currency: string;
            /** Profile Version */
            profile_version: number;
            /** Recommended Strategy Id */
            recommended_strategy_id: string;
            /** Strategies */
            strategies: components["schemas"]["StrategyProposalResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RecommendationCreate */
        RecommendationCreate: {
            /** Contribution */
            contribution: number | string;
        };
        /** RecommendationLineResponse */
        RecommendationLineResponse: {
            /** Asset Id */
            asset_id: string;
            /** Lots */
            lots: number;
            /** Lot Size */
            lot_size: number;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Current Value */
            current_value: string;
            /** Target Value */
            target_value: string;
            /** Pre Drift */
            pre_drift: string;
            /** Post Drift */
            post_drift: string;
            /** Gross */
            gross: string;
            /** Fee */
            fee: string;
            /** Total */
            total: string;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Algorithm Version */
            algorithm_version: string;
            /** Input Hash */
            input_hash: string;
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Currency */
            currency: string;
            /** Contribution */
            contribution: string;
            /** Cash Buffer */
            cash_buffer: string;
            /** Investable */
            investable: string;
            /** Gross */
            gross: string;
            /** Fees */
            fees: string;
            /** Spent */
            spent: string;
            /** Leftover */
            leftover: string;
            /** Reason */
            reason: string;
            /** Lines */
            lines: components["schemas"]["RecommendationLineResponse"][];
            /**
             * Mode
             * @default manual
             * @enum {string}
             */
            mode: "manual" | "automatic";
            /** Policy Version */
            policy_version?: string | null;
            /** Horizon Years */
            horizon_years?: number | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Candidates */
            candidates?: components["schemas"]["DiscoveryCandidateResponse"][];
            /** Rejected Candidates */
            rejected_candidates?: components["schemas"]["RejectedDiscoveryCandidateResponse"][];
            /** Profile Version */
            profile_version?: number | null;
        };
        /** RejectedDiscoveryCandidateResponse */
        RejectedDiscoveryCandidateResponse: {
            /** Asset Id */
            asset_id: string;
            /** Name */
            name: string;
            /**
             * Instrument Type
             * @enum {string}
             */
            instrument_type: "ofz" | "equity_index_fund";
            /** Reason */
            reason: string;
            /** Unit Price */
            unit_price: string;
            /** Lot Size */
            lot_size: number;
            /** Lot Cost */
            lot_cost: string;
            /**
             * Price As Of
             * Format: date-time
             */
            price_as_of: string;
            /** Source Url */
            source_url: string;
        };
        /** StrategyProposalResponse */
        StrategyProposalResponse: {
            /** Strategy Id */
            strategy_id: string;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /** Why */
            why: string;
            /** Risk Note */
            risk_note: string;
            /** Tradeoffs */
            tradeoffs: string[];
            /** Recommended */
            recommended: boolean;
            recommendation: components["schemas"]["RecommendationResponse"];
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Asset Id */
            asset_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number | string;
            /**
             * Accrued Interest Total
             * @default 0.00
             */
            accrued_interest_total: number | string;
            /** Fee */
            fee: number | string;
            /** Currency */
            currency: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Note */
            note?: string | null;
        };
        /** TransactionDraftDecisionCreate */
        TransactionDraftDecisionCreate: {
            /** Expected Version */
            expected_version: number;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "reject";
            transaction?: components["schemas"]["TransactionCreate"] | null;
        };
        /** TransactionDraftDecisionResponse */
        TransactionDraftDecisionResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "reject";
            transaction: components["schemas"]["TransactionResponse"] | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
        };
        /** TransactionDraftFields */
        TransactionDraftFields: {
            /** Side */
            side?: ("BUY" | "SELL") | null;
            /** Asset Id */
            asset_id?: string | null;
            /** Asset Name */
            asset_name?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Unit Price */
            unit_price?: string | null;
            /** Accrued Interest Total */
            accrued_interest_total?: string | null;
            /** Fee */
            fee?: string | null;
            /** Currency */
            currency?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** TransactionDraftManualCreate */
        TransactionDraftManualCreate: {
            /** Asset Id */
            asset_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number | string;
            /** Accrued Interest Total */
            accrued_interest_total: number | string;
            /** Fee */
            fee: number | string;
            /** Currency */
            currency: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Note */
            note?: string | null;
        };
        /** TransactionDraftResponse */
        TransactionDraftResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unconfirmed" | "confirmed" | "rejected";
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "text" | "image" | "manual";
            /** Source Sha256 */
            source_sha256: string;
            /** Source Metadata */
            source_metadata: {
                [key: string]: string | number;
            };
            /** Extractor Version */
            extractor_version: string;
            fields: components["schemas"]["TransactionDraftFields"];
            /** Unknown Fields */
            unknown_fields: string[];
            /** Conflicts */
            conflicts: string[];
            /** Field Confidence */
            field_confidence: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            decision: components["schemas"]["TransactionDraftDecisionResponse"] | null;
        };
        /** TransactionDraftTextCreate */
        TransactionDraftTextCreate: {
            /** Text */
            text: string;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Asset Id */
            asset_id: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Accrued Interest Total */
            accrued_interest_total: string;
            /** Fee */
            fee: string;
            /** Currency */
            currency: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_get_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_put_v1_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assets_get_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    asset_put_v1_assets__asset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    price_post_v1_assets__asset_id__prices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_post_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_draft_text_post_v1_transaction_drafts_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionDraftTextCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDraftResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_draft_manual_post_v1_transaction_drafts_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionDraftManualCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDraftResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_draft_image_post_v1_transaction_drafts_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_transaction_draft_image_post_v1_transaction_drafts_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDraftResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_draft_get_v1_transaction_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDraftResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_draft_decision_post_v1_transaction_drafts__draft_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionDraftDecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDraftResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    portfolio_get_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendation_post_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    discovery_recommendation_post_v1_discovery_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryRecommendationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    proposal_set_post_v1_proposal_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalSetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalSetResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    proposal_set_get_v1_proposal_sets__proposal_set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalSetResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendation_get_v1_recommendations__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
