/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Get */
        get: operations["profile_get_v1_profile_get"];
        /** Profile Put */
        put: operations["profile_put_v1_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assets Get */
        get: operations["assets_get_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Asset Put */
        put: operations["asset_put_v1_assets__asset_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{asset_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price Post */
        post: operations["price_post_v1_assets__asset_id__prices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Post */
        post: operations["transaction_post_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Get */
        get: operations["portfolio_get_v1_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommendation Post */
        post: operations["recommendation_post_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendation Get */
        get: operations["recommendation_get_v1_recommendations__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetListResponse */
        AssetListResponse: {
            /** Assets */
            assets: components["schemas"]["AssetResponse"][];
        };
        /** AssetPut */
        AssetPut: {
            /** Expected Version */
            expected_version?: number | null;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Lot Size */
            lot_size: number;
            /** Target Weight */
            target_weight: number | string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** AssetResponse */
        AssetResponse: {
            /** Asset Id */
            asset_id: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Lot Size */
            lot_size: number;
            /** Target Weight */
            target_weight: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** PortfolioAssetResponse */
        PortfolioAssetResponse: {
            /** Asset Id */
            asset_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Currency */
            currency: string;
            /** Latest Price */
            latest_price: string;
            /**
             * Price As Of
             * Format: date-time
             */
            price_as_of: string;
            /** Market Value */
            market_value: string;
            /** Cost Basis */
            cost_basis: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
            /** Target Weight */
            target_weight: string;
            /** Actual Weight */
            actual_weight: string;
            /** Drift */
            drift: string;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Currency */
            currency: string;
            /** Total Market Value */
            total_market_value: string;
            /** Total Cost Basis */
            total_cost_basis: string;
            /** Total Unrealized Pnl */
            total_unrealized_pnl: string;
            /** Assets */
            assets: components["schemas"]["PortfolioAssetResponse"][];
        };
        /** PriceCreate */
        PriceCreate: {
            /** Price */
            price: number | string;
            /** Currency */
            currency: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Max Age Seconds */
            max_age_seconds: number;
            /** Source */
            source: string;
        };
        /** PriceResponse */
        PriceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Asset Id */
            asset_id: string;
            /** Price */
            price: string;
            /** Currency */
            currency: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Max Age Seconds */
            max_age_seconds: number;
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfilePut */
        ProfilePut: {
            /** Expected Version */
            expected_version?: number | null;
            /** Base Currency */
            base_currency: string;
            /** Investment Horizon Years */
            investment_horizon_years: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "conservative" | "balanced" | "growth";
            /** Cash Buffer */
            cash_buffer: number | string;
            /** Broker Name */
            broker_name: string;
            /** Fee Rate */
            fee_rate: number | string;
            /** Minimum Fee */
            minimum_fee: number | string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Version */
            version: number;
            /** Base Currency */
            base_currency: string;
            /** Investment Horizon Years */
            investment_horizon_years: number;
            /** Risk Level */
            risk_level: string;
            /** Cash Buffer */
            cash_buffer: string;
            /** Broker Name */
            broker_name: string;
            /** Fee Rate */
            fee_rate: string;
            /** Minimum Fee */
            minimum_fee: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RecommendationCreate */
        RecommendationCreate: {
            /** Contribution */
            contribution: number | string;
        };
        /** RecommendationLineResponse */
        RecommendationLineResponse: {
            /** Asset Id */
            asset_id: string;
            /** Lots */
            lots: number;
            /** Lot Size */
            lot_size: number;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Current Value */
            current_value: string;
            /** Target Value */
            target_value: string;
            /** Pre Drift */
            pre_drift: string;
            /** Post Drift */
            post_drift: string;
            /** Gross */
            gross: string;
            /** Fee */
            fee: string;
            /** Total */
            total: string;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Algorithm Version */
            algorithm_version: string;
            /** Input Hash */
            input_hash: string;
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Currency */
            currency: string;
            /** Contribution */
            contribution: string;
            /** Cash Buffer */
            cash_buffer: string;
            /** Investable */
            investable: string;
            /** Gross */
            gross: string;
            /** Fees */
            fees: string;
            /** Spent */
            spent: string;
            /** Leftover */
            leftover: string;
            /** Reason */
            reason: string;
            /** Lines */
            lines: components["schemas"]["RecommendationLineResponse"][];
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Asset Id */
            asset_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number | string;
            /** Fee */
            fee: number | string;
            /** Currency */
            currency: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Note */
            note?: string | null;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Asset Id */
            asset_id: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Fee */
            fee: string;
            /** Currency */
            currency: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_get_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_put_v1_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assets_get_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    asset_put_v1_assets__asset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    price_post_v1_assets__asset_id__prices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_post_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    portfolio_get_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendation_post_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendation_get_v1_recommendations__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
